server:
  port: 8090
spring:
  application:
    name: ApiGatewayService
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: AUTHENTICATIONSERVICE
          uri: lb://AUTHENTICATIONSERVICE
          predicates:
            - Path=/fin/auth/**,/fin/users/**,/fin/admin/**
          filters:
            - AuthenticationFilter
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka